### ISSUE TITLE
can login with google but keep going to login page

### ISSUE THREAD

**Issue by ghost** [MayorFalomo/Twitter-clone#2]
![Screenshot (16)](https://github.com/MayorFalomo/Twitter-clone/assets/139623252/6c174b91-7c11-4641-8cbc-efdc8fc065b9)

**Comment by ghost** [comment]
#bug i don't know

**Comment by MayorFalomo** [comment]
> #bug i don't know

Hi Ikiitech. 
Can you describe the issue or tell me how to reproduce it so i can fix this?

**Comment by MayorFalomo** [comment]
> > #bug i don't know
> 
> Hi Ikiitech. Can you describe the issue or tell me how to reproduce it so i can fix this?

Hi @ikiitech I've resolved this issue locally already thank you, a line of code was what was triggering the error and causing it to route users back to the login, So massive thank you for drawing my attention to this!

By the way I'm working on more updates like blocking or muting another user, maybe do a better job with the trend section, improve the overall UI and whatever other advanced feature I can add, I'd love if you could help me test them features, if you'd be willing?
